AWSTemplateFormatVersion: "2010-09-09"

Description:
    A template for creating SSM parameters from a list of common parameters.

Parameters:

    InstanceType:
        Type: String
        Description: The instance type for the ec2 host
        Default: "t2.micro"

    RdsInstanceType:
        Type: String
        Description: The instance type for the ec2 host
        Default: "db.t2.micro"        

    FlaskApp:
        Type: String
        Default: microblog.py

    PostgresUser:
        Type: String
        Default: employee_usr

    PostgresDb:
        Type: String
        Default: employee_db

Resources:

  FlaskAppParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres username
      Name: FlaskApp
      Type: String
      Value: !Ref FlaskApp

  UserParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres username
      Name: PostgresUser
      Type: String
      Value: !Ref PostgresUser

  DbNameParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres db name
      Name: PostgresDb
      Type: String
      Value: !Ref PostgresDb

  Ec2InstanceTypeParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the ec2 instance type
      Name: Ec2InstanceType
      Type: String
      Value: !Ref InstanceType

  RdsInstanceTypeParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the ec2 instance type
      Name: RdsInstanceType
      Type: String
      Value: !Ref RdsInstanceType

  DbPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: PostgresRdsDbSecretPwd
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "employee_usr"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
    